- job:
    name: cyborg-grenade
    description: |
      Grenade job that performs upgrade from previous release(N-1) to
      current release(N).
    parent: grenade
    required-projects: &base_required_projects_master
      - openstack/cyborg
      - openstack/python-cyborgclient
      - openstack/cyborg-tempest-plugin
    vars: &grenade_vars
      devstack_plugins: &cyborg_devstack_plugins
        cyborg: https://opendev.org/openstack/cyborg
      devstack_services: &cyborg_devstack_services
        tempest: true
        s-account: false
        s-container: false
        s-object: false
        s-proxy: false
        c-api: false
        c-bak: false
        c-sch: false
        c-vol: false
        cinder: false
      tempest_plugins:
        - cyborg-tempest-plugin
      tempest_test_regex: cyborg_tempest_plugin
      tox_envlist: all
    irrelevant-files: &base_irrelevant_files
      - ^.*\.rst$
      - ^doc/.*$
      - ^setup.cfg$
      - ^releasenotes/.*$
      - ^(test-|)requirements.txt$
      - ^.git.*$
      - ^tox.ini$

- job:
    name: cyborg-grenade-skip-level-always
    description: |
      Grenade job that skips the previous release, validating that projects
      can support upgrades from N-2 to N release. It will always upgrade
      to the current branch. For example: If N-2 is 2025.1 release then N
      would be 2026.1.
    parent: grenade-skip-level-always
    required-projects: *base_required_projects_master
    vars: *grenade_vars
    irrelevant-files: *base_irrelevant_files

- job:
    name: cyborg-multinode-tempest
    parent: devstack-tempest
    nodeset: openstack-two-node-noble
    description: |
      Cyborg multinode devstack tempest job
    required-projects: *base_required_projects_master
    irrelevant-files: *base_irrelevant_files
    vars:
      devstack_plugins: *cyborg_devstack_plugins
      devstack_services:
        <<: *cyborg_devstack_services
        cyborg-agent: false
      tempest_plugins:
        - cyborg-tempest-plugin
      tempest_test_regex: cyborg_tempest_plugin
      tox_envlist: all
    group-vars:
      subnode:
        devstack_plugins: *cyborg_devstack_plugins
        devstack_services:
          <<: *cyborg_devstack_services
          cyborg-api: false
          cyborg-cond: false
          tempest: false

- project:
    templates:
      - openstack-cover-jobs
      - check-requirements
      - release-notes-jobs-python3
      - publish-openstack-docs-pti
      - openstack-python3-jobs
    check:
      jobs:
        - cyborg-tempest:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
        - cyborg-tempest-ipv6-only:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
        - cyborg-grenade:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
        - cyborg-grenade-skip-level-always:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
    gate:
      jobs:
        - cyborg-tempest:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
        - cyborg-grenade:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
        - cyborg-grenade-skip-level-always:
            vars:
              tempest_exclude_regex: test_delete_accelerator_request_by_instance_uuid
