# variables in path
accelerator_request_uuid:
  description: |
    The UUID of one accelerator request.
  in: path
  required: true
  type: string
deployable_uuid:
  description: |
    The UUID of the deployable.
    This must be a valid UUID otherwise API will return 400.
  in: path
  required: true
  type: string
device_profile_name:
  description: |
    The display name of a device profile.
  in: path
  required: true
  type: string
device_profile_uuid:
  description: |
    The UUID of the device_profile for your accelerator request.
    This must be a valid UUID otherwise API will return 400.
  in: path
  required: true
  type: string
device_uuid:
  description: |
    The UUID of the device.
    This must be a valid UUID otherwise API will return 400.
  in: path
  required: true
  type: string
# variables in body
device_prof_groups_req:
  description: |
    This is a list of dictionaries to describe requested accelerator resource
    by users, where users use keys to describe the resource_classes or traits
    and values to indicate its quantity or property. This is intentionally
    similar to extra_specs in nova flavor, and uses the same keywords for
    resources and traits. The key-value pair can either be a resource/trait
    or a Cyborg property. Cyborg property is of the form
    "accel:<key>": "<value>". The valid key-value pairs can be found
    `below <https://opendev.org/openstack/cyborg-specs/src/branch/master/specs/train/approved/device-profiles.rst#valid-accel-keys>`_.
  in: body
  required: true
  type: a list of dictionaries
device_prof_name_req:
  description: |
    The display name of a device profile.
  in: body
  required: true
  type: string
device_rp_uuid_bind_unbind_req:
  description: |
    UUID of the target accelerator (resource provider) for bind or unbind of
    one accelerator request.
  in: body
  required: true
  type: string
hostname_bind_unbind_req:
  description: |
    The name of the target host for bind or unbind of one accelerator request.
  in: body
  required: true
  type: string
instance_uuid_bind_unbind_req:
  description: |
    UUID of the target instance for bind or unbind of one accelerator request.
  in: body
  required: true
  type: string
